graph TD
  PLAN_NIM_1["PLAN-NIM-1\nplan\nstatus: needs-review"]
  __TASK_TDD_S_9__["[[TASK-TDD-S-9]]\nexternal\nstatus: unknown"]
  PLAN_NIM_R["PLAN-NIM-R\nplan\nstatus: in-progress"]
  __PHASE_0__["[[PHASE-0]]\nexternal\nstatus: unknown"]
  __PHASE_1__["[[PHASE-1]]\nexternal\nstatus: unknown"]
  __PHASE_2__["[[PHASE-2]]\nexternal\nstatus: unknown"]
  __PHASE_3__["[[PHASE-3]]\nexternal\nstatus: unknown"]
  __PHASE_4__["[[PHASE-4]]\nexternal\nstatus: unknown"]
  PLAN_TEST_PLAN["PLAN-TEST-PLAN\nplan\nstatus: needs-review"]
  PHASE_0["PHASE-0\nphase\nstatus: unstarted"]
  __TASK_D1__["[[TASK-D1]]\nexternal\nstatus: unknown"]
  __TASK_D2__["[[TASK-D2]]\nexternal\nstatus: unknown"]
  __TASK_D3__["[[TASK-D3]]\nexternal\nstatus: unknown"]
  __TASK_D4__["[[TASK-D4]]\nexternal\nstatus: unknown"]
  __TASK_D5__["[[TASK-D5]]\nexternal\nstatus: unknown"]
  __TASK_D6__["[[TASK-D6]]\nexternal\nstatus: unknown"]
  NIM_R["NIM-R\nexternal\nstatus: unknown"]
  PHASE_1["PHASE-1\nphase\nstatus: needs-review"]
  PHASE_4["PHASE-4\nphase\nstatus: needs-review"]
  PHASE_2["PHASE-2\nphase\nstatus: needs-review"]
  PHASE_3["PHASE-3\nphase\nstatus: in-progress"]
  PHASE_2_TDD["PHASE-2-TDD\nphase\nstatus: needs-review"]
  TASK_TDD_S_8["TASK-TDD-S-8\ntask\nstatus: needs-review"]
  __PHASE_2_TDD__["[[PHASE-2-TDD]]\nexternal\nstatus: unknown"]
  TASK_TDD_S_6["TASK-TDD-S-6\ntask\nstatus: needs-review"]
  TASK_TDD_S_9["TASK-TDD-S-9\ntask\nstatus: needs-review"]
  TASK_S_9_5["TASK-S-9.5\ntask\nstatus: needs-review"]
  __TASK_S_2__["[[TASK-S-2]]\nexternal\nstatus: unknown"]
  __TASK_S_3__["[[TASK-S-3]]\nexternal\nstatus: unknown"]
  __TASK_S_5__["[[TASK-S-5]]\nexternal\nstatus: unknown"]
  __TASK_S_6__["[[TASK-S-6]]\nexternal\nstatus: unknown"]
  TASK_TDD_S_2["TASK-TDD-S-2\ntask\nstatus: needs-review"]
  TASK_TDD_S_3["TASK-TDD-S-3\ntask\nstatus: needs-review"]
  TASK_TDD_S_7["TASK-TDD-S-7\ntask\nstatus: needs-review"]
  TASK_TDD_S_4["TASK-TDD-S-4\ntask\nstatus: needs-review"]
  TASK_TDD_S_1["TASK-TDD-S-1\ntask\nstatus: needs-review"]
  TASK_TDD_S_5["TASK-TDD-S-5\ntask\nstatus: needs-review"]
  TASK_E06["TASK-E06\ntask\nstatus: unstarted"]
  __TASK_E00__["[[TASK-E00]]\nexternal\nstatus: unknown"]
  TASK_E15["TASK-E15\ntask\nstatus: unstarted"]
  __TASK_S_1__["[[TASK-S-1]]\nexternal\nstatus: unknown"]
  __TASK_S_9__["[[TASK-S-9]]\nexternal\nstatus: unknown"]
  __TASK_E01__["[[TASK-E01]]\nexternal\nstatus: unknown"]
  TASK_E09["TASK-E09\ntask\nstatus: unstarted"]
  __TASK_S_4__["[[TASK-S-4]]\nexternal\nstatus: unknown"]
  TASK_E14["TASK-E14\ntask\nstatus: unstarted"]
  __TASK_S_8__["[[TASK-S-8]]\nexternal\nstatus: unknown"]
  TASK_E01["TASK-E01\ntask\nstatus: needs-review"]
  TASK_E03["TASK-E03\ntask\nstatus: unstarted"]
  TASK_E10["TASK-E10\ntask\nstatus: unstarted"]
  __TASK_S_7__["[[TASK-S-7]]\nexternal\nstatus: unknown"]
  TASK_E04["TASK-E04\ntask\nstatus: unstarted"]
  TASK_E02["TASK-E02\ntask\nstatus: unstarted"]
  TASK_E11["TASK-E11\ntask\nstatus: unstarted"]
  TASK_E07["TASK-E07\ntask\nstatus: unstarted"]
  TASK_E13["TASK-E13\ntask\nstatus: unstarted"]
  TASK_E08["TASK-E08\ntask\nstatus: unstarted"]
  TASK_E05["TASK-E05\ntask\nstatus: unstarted"]
  TASK_E12["TASK-E12\ntask\nstatus: unstarted"]
  TASK_S_1["TASK-S-1\ntask\nstatus: needs-review"]
  __TASK_TDD_S_1__["[[TASK-TDD-S-1]]\nexternal\nstatus: unknown"]
  TASK_S_7["TASK-S-7\ntask\nstatus: needs-review"]
  __TASK_TDD_S_7__["[[TASK-TDD-S-7]]\nexternal\nstatus: unknown"]
  TASK_S_3["TASK-S-3\ntask\nstatus: needs-review"]
  __TASK_TDD_S_3__["[[TASK-TDD-S-3]]\nexternal\nstatus: unknown"]
  TASK_S_9["TASK-S-9\ntask\nstatus: needs-review"]
  TASK_S_4["TASK-S-4\ntask\nstatus: needs-review"]
  __TASK_TDD_S_4__["[[TASK-TDD-S-4]]\nexternal\nstatus: unknown"]
  TASK_S_6["TASK-S-6\ntask\nstatus: needs-review"]
  __TASK_TDD_S_6__["[[TASK-TDD-S-6]]\nexternal\nstatus: unknown"]
  TASK_S_2["TASK-S-2\ntask\nstatus: needs-review"]
  __TASK_TDD_S_2__["[[TASK-TDD-S-2]]\nexternal\nstatus: unknown"]
  TASK_S_8["TASK-S-8\ntask\nstatus: needs-review"]
  __TASK_TDD_S_8__["[[TASK-TDD-S-8]]\nexternal\nstatus: unknown"]
  TASK_S_5["TASK-S-5\ntask\nstatus: needs-review"]
  __TASK_TDD_S_5__["[[TASK-TDD-S-5]]\nexternal\nstatus: unknown"]
  TASK_S_10["TASK-S-10\ntask\nstatus: needs-review"]
  TASK_E00["TASK-E00\ntask\nstatus: needs-review"]
  TASK_D3["TASK-D3\ntask\nstatus: unstarted"]
  TASK_D5["TASK-D5\ntask\nstatus: unstarted"]
  TASK_D4["TASK-D4\ntask\nstatus: unstarted"]
  TASK_D2["TASK-D2\ntask\nstatus: unstarted"]
  TASK_D6["TASK-D6\ntask\nstatus: unstarted"]
  TASK_D1["TASK-D1\ntask\nstatus: unstarted"]
  __TASK_TDD_S_9__ --> PLAN_NIM_1
  __PHASE_0__ --> PLAN_NIM_R
  __PHASE_1__ --> PLAN_NIM_R
  __PHASE_2__ --> PLAN_NIM_R
  __PHASE_3__ --> PLAN_NIM_R
  __PHASE_4__ --> PLAN_NIM_R
  __TASK_D1__ --> PHASE_0
  __TASK_D2__ --> PHASE_0
  __TASK_D3__ --> PHASE_0
  __TASK_D4__ --> PHASE_0
  __TASK_D5__ --> PHASE_0
  __TASK_D6__ --> PHASE_0
  NIM_R --> PHASE_0
  NIM_R --> PHASE_1
  __PHASE_0__ --> PHASE_4
  __PHASE_1__ --> PHASE_4
  __PHASE_2__ --> PHASE_4
  __PHASE_3__ --> PHASE_4
  NIM_R --> PHASE_4
  NIM_R --> PHASE_2
  NIM_R --> PHASE_3
  PHASE_2 --> PHASE_2_TDD
  __PHASE_2_TDD__ --> TASK_TDD_S_8
  __PHASE_2_TDD__ --> TASK_TDD_S_6
  __PHASE_2_TDD__ --> TASK_TDD_S_9
  __TASK_S_2__ --> TASK_S_9_5
  __TASK_S_3__ --> TASK_S_9_5
  __TASK_S_5__ --> TASK_S_9_5
  __TASK_S_6__ --> TASK_S_9_5
  __PHASE_2_TDD__ --> TASK_S_9_5
  __PHASE_2_TDD__ --> TASK_TDD_S_2
  __PHASE_2_TDD__ --> TASK_TDD_S_3
  __PHASE_2_TDD__ --> TASK_TDD_S_7
  __PHASE_2_TDD__ --> TASK_TDD_S_4
  __PHASE_2_TDD__ --> TASK_TDD_S_1
  __PHASE_2_TDD__ --> TASK_TDD_S_5
  __TASK_S_5__ --> TASK_E06
  __TASK_S_6__ --> TASK_E06
  __TASK_D2__ --> TASK_E06
  __TASK_E00__ --> TASK_E06
  __PHASE_3__ --> TASK_E06
  __TASK_S_1__ --> TASK_E15
  __TASK_S_9__ --> TASK_E15
  __TASK_E00__ --> TASK_E15
  __TASK_E01__ --> TASK_E15
  __PHASE_3__ --> TASK_E15
  __TASK_S_4__ --> TASK_E09
  __TASK_S_5__ --> TASK_E09
  __TASK_D4__ --> TASK_E09
  __TASK_E00__ --> TASK_E09
  __PHASE_3__ --> TASK_E09
  __TASK_S_6__ --> TASK_E14
  __TASK_S_8__ --> TASK_E14
  __TASK_D1__ --> TASK_E14
  __TASK_E00__ --> TASK_E14
  __PHASE_3__ --> TASK_E14
  __TASK_S_9__ --> TASK_E01
  __TASK_E00__ --> TASK_E01
  __PHASE_3__ --> TASK_E01
  __TASK_S_2__ --> TASK_E03
  __TASK_S_5__ --> TASK_E03
  __TASK_S_6__ --> TASK_E03
  __TASK_D1__ --> TASK_E03
  __TASK_D2__ --> TASK_E03
  __TASK_E00__ --> TASK_E03
  __PHASE_3__ --> TASK_E03
  __TASK_S_3__ --> TASK_E10
  __TASK_S_5__ --> TASK_E10
  __TASK_S_7__ --> TASK_E10
  __TASK_E00__ --> TASK_E10
  __PHASE_3__ --> TASK_E10
  __TASK_S_2__ --> TASK_E04
  __TASK_S_3__ --> TASK_E04
  __TASK_S_5__ --> TASK_E04
  __TASK_D2__ --> TASK_E04
  __TASK_E00__ --> TASK_E04
  __PHASE_3__ --> TASK_E04
  __TASK_S_4__ --> TASK_E02
  __TASK_S_6__ --> TASK_E02
  __TASK_D3__ --> TASK_E02
  __TASK_D4__ --> TASK_E02
  __TASK_D5__ --> TASK_E02
  __TASK_E00__ --> TASK_E02
  __PHASE_3__ --> TASK_E02
  __TASK_S_5__ --> TASK_E11
  __TASK_S_6__ --> TASK_E11
  __TASK_D5__ --> TASK_E11
  __TASK_E00__ --> TASK_E11
  __PHASE_3__ --> TASK_E11
  __TASK_S_2__ --> TASK_E07
  __TASK_S_4__ --> TASK_E07
  __TASK_S_5__ --> TASK_E07
  __TASK_S_6__ --> TASK_E07
  __TASK_D3__ --> TASK_E07
  __TASK_D4__ --> TASK_E07
  __TASK_D5__ --> TASK_E07
  __TASK_E00__ --> TASK_E07
  __PHASE_3__ --> TASK_E07
  __TASK_S_2__ --> TASK_E13
  __TASK_S_4__ --> TASK_E13
  __TASK_S_5__ --> TASK_E13
  __TASK_S_6__ --> TASK_E13
  __TASK_S_8__ --> TASK_E13
  __TASK_D1__ --> TASK_E13
  __TASK_D2__ --> TASK_E13
  __TASK_D6__ --> TASK_E13
  __TASK_E00__ --> TASK_E13
  __PHASE_3__ --> TASK_E13
  __TASK_S_5__ --> TASK_E08
  __TASK_S_6__ --> TASK_E08
  __TASK_D1__ --> TASK_E08
  __TASK_E00__ --> TASK_E08
  __PHASE_3__ --> TASK_E08
  __TASK_S_3__ --> TASK_E05
  __TASK_S_5__ --> TASK_E05
  __TASK_E00__ --> TASK_E05
  __PHASE_3__ --> TASK_E05
  __TASK_S_2__ --> TASK_E12
  __TASK_S_4__ --> TASK_E12
  __TASK_S_5__ --> TASK_E12
  __TASK_S_6__ --> TASK_E12
  __TASK_S_8__ --> TASK_E12
  __TASK_D1__ --> TASK_E12
  __TASK_D2__ --> TASK_E12
  __TASK_D6__ --> TASK_E12
  __TASK_E00__ --> TASK_E12
  __PHASE_3__ --> TASK_E12
  __TASK_TDD_S_1__ --> TASK_S_1
  __PHASE_2__ --> TASK_S_1
  __TASK_S_4__ --> TASK_S_7
  __TASK_S_5__ --> TASK_S_7
  __TASK_TDD_S_7__ --> TASK_S_7
  __PHASE_2__ --> TASK_S_7
  __TASK_S_1__ --> TASK_S_3
  __TASK_TDD_S_3__ --> TASK_S_3
  __PHASE_2__ --> TASK_S_3
  __TASK_S_7__ --> TASK_S_9
  __TASK_TDD_S_9__ --> TASK_S_9
  __PHASE_2__ --> TASK_S_9
  __TASK_S_2__ --> TASK_S_4
  __TASK_S_3__ --> TASK_S_4
  __TASK_TDD_S_4__ --> TASK_S_4
  __PHASE_2__ --> TASK_S_4
  __TASK_S_4__ --> TASK_S_6
  __TASK_S_5__ --> TASK_S_6
  __TASK_TDD_S_6__ --> TASK_S_6
  __PHASE_2__ --> TASK_S_6
  __TASK_S_1__ --> TASK_S_2
  __TASK_TDD_S_2__ --> TASK_S_2
  __PHASE_2__ --> TASK_S_2
  __TASK_S_5__ --> TASK_S_8
  __TASK_S_6__ --> TASK_S_8
  __TASK_TDD_S_8__ --> TASK_S_8
  __PHASE_2__ --> TASK_S_8
  __TASK_S_3__ --> TASK_S_5
  __TASK_S_4__ --> TASK_S_5
  __TASK_TDD_S_5__ --> TASK_S_5
  __PHASE_2__ --> TASK_S_5
  __TASK_S_8__ --> TASK_S_10
  __TASK_S_9__ --> TASK_S_10
  __TASK_TDD_S_1__ --> TASK_S_10
  __TASK_TDD_S_2__ --> TASK_S_10
  __TASK_TDD_S_3__ --> TASK_S_10
  __TASK_TDD_S_4__ --> TASK_S_10
  __TASK_TDD_S_5__ --> TASK_S_10
  __TASK_TDD_S_6__ --> TASK_S_10
  __TASK_TDD_S_7__ --> TASK_S_10
  __TASK_TDD_S_8__ --> TASK_S_10
  __TASK_TDD_S_9__ --> TASK_S_10
  __PHASE_2__ --> TASK_S_10
  __PHASE_4__ --> TASK_S_10
  __PHASE_1__ --> TASK_E00
  __PHASE_0__ --> TASK_D3
  __PHASE_0__ --> TASK_D5
  __PHASE_0__ --> TASK_D4
  __PHASE_0__ --> TASK_D2
  __PHASE_0__ --> TASK_D6
  __PHASE_0__ --> TASK_D1
